#!/usr/bin/env bash
# Regenerate the example outputs using the bundled skill scripts.
# Doubles as a smoke test of the whole skill set against the live API.
#
# Usage:
#   export GRADIUM_API_KEY=...
#   ./generate.sh            # audio + subtitle examples (a few cents of credits)
#   ./generate.sh --video    # also render the Pruna talking-video example
#                            # (needs PRUNA_API_KEY and a portrait.png here;
#                            #  costs ~$0.15 of Pruna credits)
set -euo pipefail
cd "$(dirname "$0")"
: "${GRADIUM_API_KEY:?Set GRADIUM_API_KEY first}"

PY=${PYTHON:-python3}   # needs: pip install requests websockets
TTS=../gradium/gradium-text-to-speech/scripts/tts.py
STT=../gradium/gradium-speech-to-text/scripts/transcribe.py
S2S=../gradium/gradium-speech-translation/scripts/s2s.py

LINE="Welcome to the Gradium skill folder. Every script in here was tested against the live API."

echo "[1/5] text-to-speech (default voice)"
"$PY" "$TTS" "$LINE" --out example_tts.wav

echo "[2/5] text-to-speech (fast pace + text normalization)"
"$PY" "$TTS" "This is the fast take with rewrite rules. Dr. Smith pays \$20 on 5th Ave." \
    --speed fast --rewrite en --out example_tts_fast.wav

echo "[3/5] speech-to-text with keyword boosting + SRT subtitles"
"$PY" "$STT" example_tts.wav --language en --keywords Gradium --srt example_captions.srt

echo "[4/5] speech-to-speech: English -> French dub (Solène voice)"
"$PY" "$S2S" example_tts.wav --to fr --voice YhIHaAfQ0cQPDV9R --out example_dub_fr.wav

echo "[5/5] speech-to-speech re-voicing: same words, different voice (Zoey)"
"$PY" "$S2S" example_tts.wav --to en --voice NbpkqMVS3CJeq2j8 --out example_revoice.wav

if [[ "${1:-}" == "--video" ]]; then
    : "${PRUNA_API_KEY:?Set PRUNA_API_KEY for the video example}"
    [[ -f portrait.png ]] || { echo "Put a portrait.png in examples/ first"; exit 1; }
    echo "[bonus] Gradium voice -> Pruna talking avatar"
    "$PY" ../pruna/gradium-pruna-video/scripts/voice_video.py \
        "Hi! This voice was generated by Gradium and lip-synced by Pruna." \
        --image portrait.png --out example_avatar.mp4
fi

echo "Done. Generated files:"
ls -la example_*
